export const SET_QUESTIONS = 'SET_QUESTIONS';
export const FETCH_QUESTIONS_FAILED = 'FETCH_QUESTIONS_FAILED';
export const VALIDATE_SELECTED_OPTION = 'VALIDATE_SELECTED_OPTION';
export const NAVIGATE_NEXT_QUESTION = 'NAVIGATE_NEXT_QUESTION';
export const PLAY_QUIZ_AGAIN = 'PLAY_QUIZ_AGAIN';
